"""Arquivo de importações das classes de Raças"""
# flake8: noqa F401
from .aggelus import Aggelus
from .anao import Anao
from .base import BaseRace
from .dahllan import Dahllan
from .elfo import Elfo
from .goblin import Goblin
from .golem import Golem
from .humano import Humano
from .hynne import Hynne
from .kliren import Kliren
from .lefou import Lefou
from .medusa import Medusa
from .minotauro import Minotauro
from .osteon import Osteon
from .qareen import Qareen
from .racas import Racas
from .sereiatritao import SereiaTritao
from .silfide import Silfide
from .sulfure import Sulfure
from .trog import Trog
from .suraggel import Suraggel
